version: "3.5"

networks:
    application:
        name: application

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        volumes:
            - .:/var/www/app
            - ./storage:/var/www/app/storage
            - ./bootstrap/cache:/var/www/app/bootstrap/cache
        networks:
            - application

    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/app
        depends_on:
            - php
        networks:
            - application
